package app.icampuspass.android.app.models

import org.json.JSONObject

class StuData {
    val jsonString = """{
    "stuelelist": [
        {
            "ch_cos_name": "資料庫設計",
            "en_cos_name": "DATA BASE DESIGN",
            "time_plase": "一/01,02/B  218 ",
            "seat_no": "036",
            "teach_name": "游佳萍",
            "teach_name_en": "YU CHIA-PING",
            "note": "",
            "week": "1",
            "sess1": "01",
            "sess2": "02",
            "sess3": "  ",
            "cos_no": "TLMXB2E0648 0C   ",
            "cos_ele_seq": "2463",
            "remark": "&nbsp;",
            "room": "B218",
            "timePlase": {
                "week": "(一)",
                "sesses": [
                    "01",
                    "02"
                ],
                "room": "B218"
            }
        },
        {
            "ch_cos_name": "經濟學",
            "en_cos_name": "ECONOMICS",
            "time_plase": "一/03/B  601 ",
            "seat_no": "031",
            "teach_name": "廖珮瑜",
            "teach_name_en": "LIAO, PEI-YU",
            "note": "                                                                                                    ",
            "week": "1",
            "sess1": "03",
            "sess2": "  ",
            "sess3": "  ",
            "cos_no": "TLMXB2B0302 2C P ",
            "cos_ele_seq": "2458",
            "remark": "&nbsp;",
            "room": "B601",
            "timePlase": {
                "week": "(一)",
                "sesses": [
                    "03"
                ],
                "room": "B601"
            }
        },
        {
            "ch_cos_name": "資料庫設計",
            "en_cos_name": "DATA BASE DESIGN",
            "time_plase": "二/03/E  201 ",
            "seat_no": "036",
            "teach_name": "助　教",
            "teach_name_en": "Assistant",
            "note": "",
            "week": "2",
            "sess1": "03",
            "sess2": "  ",
            "sess3": "  ",
            "cos_no": "TLMXB2E0648 0C P ",
            "cos_ele_seq": "2464",
            "remark": "&nbsp;",
            "room": "E201",
            "timePlase": {
                "week": "(二)",
                "sesses": [
                    "03"
                ],
                "room": "E201"
            }
        },
        {
            "ch_cos_name": "資料庫設計",
            "en_cos_name": "DATA BASE DESIGN",
            "time_plase": "二/04/E  214 ",
            "seat_no": "036",
            "teach_name": "游佳萍",
            "teach_name_en": "YU CHIA-PING",
            "note": "",
            "week": "2",
            "sess1": "04",
            "sess2": "  ",
            "sess3": "  ",
            "cos_no": "TLMXB2E0648 0C   ",
            "cos_ele_seq": "2463",
            "remark": "&nbsp;",
            "room": "E214",
            "timePlase": {
                "week": "(二)",
                "sesses": [
                    "04"
                ],
                "room": "E214"
            }
        },
        {
            "ch_cos_name": "作業系統實務(限本班生)",
            "en_cos_name": "OPERATING SYSTEM PRACTICES",
            "time_plase": "二/06,07/B  615 ",
            "seat_no": "041",
            "teach_name": "魏世杰",
            "teach_name_en": "WEI SHIH-CHIEH",
            "note": "限本班生                                                                                            ",
            "week": "2",
            "sess1": "06",
            "sess2": "07",
            "sess3": "  ",
            "cos_no": "TLMXB2M1953 0C   ",
            "cos_ele_seq": "2477",
            "remark": "&nbsp;",
            "room": "B615",
            "timePlase": {
                "week": "(二)",
                "sesses": [
                    "06",
                    "07"
                ],
                "room": "B615"
            }
        },
        {
            "ch_cos_name": "資訊安全概論(本系生、輔系及雙主修生優先選課)",
            "en_cos_name": "INTRODUCTION TO INFORMATION SECURIT",
            "time_plase": "二/08,09,10/B  428 ",
            "seat_no": "061",
            "teach_name": "李鴻璋",
            "teach_name_en": "LEE HUNG-CHANG",
            "note": "本系生、輔系及雙主修生優先選課",
            "week": "2",
            "sess1": "08",
            "sess2": "09",
            "sess3": "10",
            "cos_no": "TLMXB2M1058 0P   ",
            "cos_ele_seq": "2466",
            "remark": "&nbsp;",
            "room": "B428",
            "timePlase": {
                "week": "(二)",
                "sesses": [
                    "08",
                    "09",
                    "10"
                ],
                "room": "B428"
            }
        },
        {
            "ch_cos_name": "經濟學(限本班生)",
            "en_cos_name": "ECONOMICS",
            "time_plase": "四/01,02/B  602 ",
            "seat_no": "031",
            "teach_name": "陳炤良",
            "teach_name_en": "CHEN CHAO-LIANG",
            "note": "限本班生                                                                                            ",
            "week": "4",
            "sess1": "01",
            "sess2": "02",
            "sess3": "  ",
            "cos_no": "TLMXB2B0302 2C   ",
            "cos_ele_seq": "2457",
            "remark": "&nbsp;",
            "room": "B602",
            "timePlase": {
                "week": "(四)",
                "sesses": [
                    "01",
                    "02"
                ],
                "room": "B602"
            }
        },
        {
            "ch_cos_name": "作業系統實務",
            "en_cos_name": "OPERATING SYSTEM PRACTICES",
            "time_plase": "四/03/B  607 ",
            "seat_no": "041",
            "teach_name": "助　教",
            "teach_name_en": "Assistant",
            "note": "                                                                                                    ",
            "week": "4",
            "sess1": "03",
            "sess2": "  ",
            "sess3": "  ",
            "cos_no": "TLMXB2M1953 0C P ",
            "cos_ele_seq": "2478",
            "remark": "&nbsp;",
            "room": "B607",
            "timePlase": {
                "week": "(四)",
                "sesses": [
                    "03"
                ],
                "room": "B607"
            }
        },
        {
            "ch_cos_name": "英文（二）(加選請依英文系網頁＞最新消息＞通識外語學門公告辦理。)",
            "en_cos_name": "ENGLISH (II)",
            "time_plase": "五/01,02/L  306 ",
            "seat_no": "045",
            "teach_name": "邱智銘",
            "teach_name_en": "CHIU, CHIH-MING",
            "note": "加選請依英文系網頁＞最新消息＞通識外語學門公告辦理。",
            "week": "5",
            "sess1": "01",
            "sess2": "02",
            "sess3": "  ",
            "cos_no": "TGLEB2A0050 2BB  ",
            "cos_ele_seq": "1742",
            "remark": "&nbsp;",
            "room": "L306",
            "timePlase": {
                "week": "(五)",
                "sesses": [
                    "01",
                    "02"
                ],
                "room": "L306"
            }
        },
        {
            "ch_cos_name": "程式設計與資料結構",
            "en_cos_name": "PROGRAMMING AND DATA STRUCTURES",
            "time_plase": "五/03/B  217 ",
            "seat_no": "037",
            "teach_name": "助　教",
            "teach_name_en": "Assistant",
            "note": "                                                                                                    ",
            "week": "5",
            "sess1": "03",
            "sess2": "  ",
            "sess3": "  ",
            "cos_no": "TLMXB2M1326 2C P ",
            "cos_ele_seq": "2472",
            "remark": "&nbsp;",
            "room": "B217",
            "timePlase": {
                "week": "(五)",
                "sesses": [
                    "03"
                ],
                "room": "B217"
            }
        },
        {
            "ch_cos_name": "程式設計與資料結構(限本班生；有擋修)",
            "en_cos_name": "PROGRAMMING AND DATA STRUCTURES",
            "time_plase": "五/04/B  217 ",
            "seat_no": "037",
            "teach_name": "張昭憲",
            "teach_name_en": "CHANG JAU-SHIEN",
            "note": "限本班生；有擋修                                                                                    ",
            "week": "5",
            "sess1": "04",
            "sess2": "  ",
            "sess3": "  ",
            "cos_no": "TLMXB2M1326 2C   ",
            "cos_ele_seq": "2471",
            "remark": "&nbsp;",
            "room": "B217",
            "timePlase": {
                "week": "(五)",
                "sesses": [
                    "04"
                ],
                "room": "B217"
            }
        },
        {
            "ch_cos_name": "商事法",
            "en_cos_name": "COMMERCIAL LAW",
            "time_plase": "五/06,07/B  704 ",
            "seat_no": "044",
            "teach_name": "林智瑋",
            "teach_name_en": "CHIH-WEI LIN",
            "note": "                                                                                                    ",
            "week": "5",
            "sess1": "06",
            "sess2": "07",
            "sess3": "  ",
            "cos_no": "TLMXB2B0173 0C   ",
            "cos_ele_seq": "2452",
            "remark": "&nbsp;",
            "room": "B704",
            "timePlase": {
                "week": "(五)",
                "sesses": [
                    "06",
                    "07"
                ],
                "room": "B704"
            }
        },
        {
            "ch_cos_name": "程式設計與資料結構(限本班生；有擋修)",
            "en_cos_name": "PROGRAMMING AND DATA STRUCTURES",
            "time_plase": "五/08,09/B  218 ",
            "seat_no": "037",
            "teach_name": "張昭憲",
            "teach_name_en": "CHANG JAU-SHIEN",
            "note": "限本班生；有擋修                                                                                    ",
            "week": "5",
            "sess1": "08",
            "sess2": "09",
            "sess3": "  ",
            "cos_no": "TLMXB2M1326 2C   ",
            "cos_ele_seq": "2471",
            "remark": "&nbsp;",
            "room": "B218",
            "timePlase": {
                "week": "(五)",
                "sesses": [
                    "08",
                    "09"
                ],
                "room": "B218"
            }
        }
    ],
    "cells": [
        {
            "weekno": "1",
            "sessno": "01",
            "week": "一",
            "sesstime": "08:10",
            "seatno": "036",
            "ch_cos_name": "資料庫設計",
            "en_cos_name": "DATA BASE DESIGN",
            "teach_name": "游佳萍",
            "teach_name_en": "YU CHIA-PING",
            "note": "",
            "room": "B218"
        },
        {
            "weekno": "1",
            "sessno": "02",
            "week": "一",
            "sesstime": "09:10",
            "seatno": "036",
            "ch_cos_name": "資料庫設計",
            "en_cos_name": "DATA BASE DESIGN",
            "teach_name": "游佳萍",
            "teach_name_en": "YU CHIA-PING",
            "note": "",
            "room": "B218"
        },
        {
            "weekno": "1",
            "sessno": "03",
            "week": "一",
            "sesstime": "10:10",
            "seatno": "031",
            "ch_cos_name": "經濟學",
            "en_cos_name": "ECONOMICS",
            "teach_name": "廖珮瑜",
            "teach_name_en": "LIAO, PEI-YU",
            "note": "                                                                                                    ",
            "room": "B601"
        },
        {
            "weekno": "1",
            "sessno": "04",
            "week": "一",
            "sesstime": "11:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "1",
            "sessno": "05",
            "week": "一",
            "sesstime": "12:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "1",
            "sessno": "06",
            "week": "一",
            "sesstime": "13:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "1",
            "sessno": "07",
            "week": "一",
            "sesstime": "14:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "1",
            "sessno": "08",
            "week": "一",
            "sesstime": "15:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "1",
            "sessno": "09",
            "week": "一",
            "sesstime": "16:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "1",
            "sessno": "10",
            "week": "一",
            "sesstime": "17:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "1",
            "sessno": "11",
            "week": "一",
            "sesstime": "18:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "1",
            "sessno": "12",
            "week": "一",
            "sesstime": "19:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "1",
            "sessno": "13",
            "week": "一",
            "sesstime": "20:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "1",
            "sessno": "14",
            "week": "一",
            "sesstime": "21:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "2",
            "sessno": "01",
            "week": "二",
            "sesstime": "08:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "2",
            "sessno": "02",
            "week": "二",
            "sesstime": "09:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "2",
            "sessno": "03",
            "week": "二",
            "sesstime": "10:10",
            "seatno": "036",
            "ch_cos_name": "資料庫設計",
            "en_cos_name": "DATA BASE DESIGN",
            "teach_name": "助　教",
            "teach_name_en": "Assistant",
            "note": "",
            "room": "E201"
        },
        {
            "weekno": "2",
            "sessno": "04",
            "week": "二",
            "sesstime": "11:10",
            "seatno": "036",
            "ch_cos_name": "資料庫設計",
            "en_cos_name": "DATA BASE DESIGN",
            "teach_name": "游佳萍",
            "teach_name_en": "YU CHIA-PING",
            "note": "",
            "room": "E214"
        },
        {
            "weekno": "2",
            "sessno": "05",
            "week": "二",
            "sesstime": "12:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "2",
            "sessno": "06",
            "week": "二",
            "sesstime": "13:10",
            "seatno": "041",
            "ch_cos_name": "作業系統實務(限本班生)",
            "en_cos_name": "OPERATING SYSTEM PRACTICES",
            "teach_name": "魏世杰",
            "teach_name_en": "WEI SHIH-CHIEH",
            "note": "限本班生                                                                                            ",
            "room": "B615"
        },
        {
            "weekno": "2",
            "sessno": "07",
            "week": "二",
            "sesstime": "14:10",
            "seatno": "041",
            "ch_cos_name": "作業系統實務(限本班生)",
            "en_cos_name": "OPERATING SYSTEM PRACTICES",
            "teach_name": "魏世杰",
            "teach_name_en": "WEI SHIH-CHIEH",
            "note": "限本班生                                                                                            ",
            "room": "B615"
        },
        {
            "weekno": "2",
            "sessno": "08",
            "week": "二",
            "sesstime": "15:10",
            "seatno": "061",
            "ch_cos_name": "資訊安全概論(本系生、輔系及雙主修生優先選課)",
            "en_cos_name": "INTRODUCTION TO INFORMATION SECURIT",
            "teach_name": "李鴻璋",
            "teach_name_en": "LEE HUNG-CHANG",
            "note": "本系生、輔系及雙主修生優先選課",
            "room": "B428"
        },
        {
            "weekno": "2",
            "sessno": "09",
            "week": "二",
            "sesstime": "16:10",
            "seatno": "061",
            "ch_cos_name": "資訊安全概論(本系生、輔系及雙主修生優先選課)",
            "en_cos_name": "INTRODUCTION TO INFORMATION SECURIT",
            "teach_name": "李鴻璋",
            "teach_name_en": "LEE HUNG-CHANG",
            "note": "本系生、輔系及雙主修生優先選課",
            "room": "B428"
        },
        {
            "weekno": "2",
            "sessno": "10",
            "week": "二",
            "sesstime": "17:10",
            "seatno": "061",
            "ch_cos_name": "資訊安全概論(本系生、輔系及雙主修生優先選課)",
            "en_cos_name": "INTRODUCTION TO INFORMATION SECURIT",
            "teach_name": "李鴻璋",
            "teach_name_en": "LEE HUNG-CHANG",
            "note": "本系生、輔系及雙主修生優先選課",
            "room": "B428"
        },
        {
            "weekno": "2",
            "sessno": "11",
            "week": "二",
            "sesstime": "18:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "2",
            "sessno": "12",
            "week": "二",
            "sesstime": "19:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "2",
            "sessno": "13",
            "week": "二",
            "sesstime": "20:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "2",
            "sessno": "14",
            "week": "二",
            "sesstime": "21:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "3",
            "sessno": "01",
            "week": "三",
            "sesstime": "08:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "3",
            "sessno": "02",
            "week": "三",
            "sesstime": "09:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "3",
            "sessno": "03",
            "week": "三",
            "sesstime": "10:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "3",
            "sessno": "04",
            "week": "三",
            "sesstime": "11:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "3",
            "sessno": "05",
            "week": "三",
            "sesstime": "12:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "3",
            "sessno": "06",
            "week": "三",
            "sesstime": "13:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "3",
            "sessno": "07",
            "week": "三",
            "sesstime": "14:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "3",
            "sessno": "08",
            "week": "三",
            "sesstime": "15:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "3",
            "sessno": "09",
            "week": "三",
            "sesstime": "16:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "3",
            "sessno": "10",
            "week": "三",
            "sesstime": "17:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "3",
            "sessno": "11",
            "week": "三",
            "sesstime": "18:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "3",
            "sessno": "12",
            "week": "三",
            "sesstime": "19:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "3",
            "sessno": "13",
            "week": "三",
            "sesstime": "20:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "3",
            "sessno": "14",
            "week": "三",
            "sesstime": "21:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "4",
            "sessno": "01",
            "week": "四",
            "sesstime": "08:10",
            "seatno": "031",
            "ch_cos_name": "經濟學(限本班生)",
            "en_cos_name": "ECONOMICS",
            "teach_name": "陳炤良",
            "teach_name_en": "CHEN CHAO-LIANG",
            "note": "限本班生                                                                                            ",
            "room": "B602"
        },
        {
            "weekno": "4",
            "sessno": "02",
            "week": "四",
            "sesstime": "09:10",
            "seatno": "031",
            "ch_cos_name": "經濟學(限本班生)",
            "en_cos_name": "ECONOMICS",
            "teach_name": "陳炤良",
            "teach_name_en": "CHEN CHAO-LIANG",
            "note": "限本班生                                                                                            ",
            "room": "B602"
        },
        {
            "weekno": "4",
            "sessno": "03",
            "week": "四",
            "sesstime": "10:10",
            "seatno": "041",
            "ch_cos_name": "作業系統實務",
            "en_cos_name": "OPERATING SYSTEM PRACTICES",
            "teach_name": "助　教",
            "teach_name_en": "Assistant",
            "note": "                                                                                                    ",
            "room": "B607"
        },
        {
            "weekno": "4",
            "sessno": "04",
            "week": "四",
            "sesstime": "11:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "4",
            "sessno": "05",
            "week": "四",
            "sesstime": "12:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "4",
            "sessno": "06",
            "week": "四",
            "sesstime": "13:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "4",
            "sessno": "07",
            "week": "四",
            "sesstime": "14:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "4",
            "sessno": "08",
            "week": "四",
            "sesstime": "15:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "4",
            "sessno": "09",
            "week": "四",
            "sesstime": "16:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "4",
            "sessno": "10",
            "week": "四",
            "sesstime": "17:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "4",
            "sessno": "11",
            "week": "四",
            "sesstime": "18:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "4",
            "sessno": "12",
            "week": "四",
            "sesstime": "19:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "4",
            "sessno": "13",
            "week": "四",
            "sesstime": "20:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "4",
            "sessno": "14",
            "week": "四",
            "sesstime": "21:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "5",
            "sessno": "01",
            "week": "五",
            "sesstime": "08:10",
            "seatno": "045",
            "ch_cos_name": "英文（二）(加選請依英文系網頁＞最新消息＞通識外語學門公告辦理。)",
            "en_cos_name": "ENGLISH (II)",
            "teach_name": "邱智銘",
            "teach_name_en": "CHIU, CHIH-MING",
            "note": "加選請依英文系網頁＞最新消息＞通識外語學門公告辦理。",
            "room": "L306"
        },
        {
            "weekno": "5",
            "sessno": "02",
            "week": "五",
            "sesstime": "09:10",
            "seatno": "045",
            "ch_cos_name": "英文（二）(加選請依英文系網頁＞最新消息＞通識外語學門公告辦理。)",
            "en_cos_name": "ENGLISH (II)",
            "teach_name": "邱智銘",
            "teach_name_en": "CHIU, CHIH-MING",
            "note": "加選請依英文系網頁＞最新消息＞通識外語學門公告辦理。",
            "room": "L306"
        },
        {
            "weekno": "5",
            "sessno": "03",
            "week": "五",
            "sesstime": "10:10",
            "seatno": "037",
            "ch_cos_name": "程式設計與資料結構",
            "en_cos_name": "PROGRAMMING AND DATA STRUCTURES",
            "teach_name": "助　教",
            "teach_name_en": "Assistant",
            "note": "                                                                                                    ",
            "room": "B217"
        },
        {
            "weekno": "5",
            "sessno": "04",
            "week": "五",
            "sesstime": "11:10",
            "seatno": "037",
            "ch_cos_name": "程式設計與資料結構(限本班生；有擋修)",
            "en_cos_name": "PROGRAMMING AND DATA STRUCTURES",
            "teach_name": "張昭憲",
            "teach_name_en": "CHANG JAU-SHIEN",
            "note": "限本班生；有擋修                                                                                    ",
            "room": "B217"
        },
        {
            "weekno": "5",
            "sessno": "05",
            "week": "五",
            "sesstime": "12:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "5",
            "sessno": "06",
            "week": "五",
            "sesstime": "13:10",
            "seatno": "044",
            "ch_cos_name": "商事法",
            "en_cos_name": "COMMERCIAL LAW",
            "teach_name": "林智瑋",
            "teach_name_en": "CHIH-WEI LIN",
            "note": "                                                                                                    ",
            "room": "B704"
        },
        {
            "weekno": "5",
            "sessno": "07",
            "week": "五",
            "sesstime": "14:10",
            "seatno": "044",
            "ch_cos_name": "商事法",
            "en_cos_name": "COMMERCIAL LAW",
            "teach_name": "林智瑋",
            "teach_name_en": "CHIH-WEI LIN",
            "note": "                                                                                                    ",
            "room": "B704"
        },
        {
            "weekno": "5",
            "sessno": "08",
            "week": "五",
            "sesstime": "15:10",
            "seatno": "037",
            "ch_cos_name": "程式設計與資料結構(限本班生；有擋修)",
            "en_cos_name": "PROGRAMMING AND DATA STRUCTURES",
            "teach_name": "張昭憲",
            "teach_name_en": "CHANG JAU-SHIEN",
            "note": "限本班生；有擋修                                                                                    ",
            "room": "B218"
        },
        {
            "weekno": "5",
            "sessno": "09",
            "week": "五",
            "sesstime": "16:10",
            "seatno": "037",
            "ch_cos_name": "程式設計與資料結構(限本班生；有擋修)",
            "en_cos_name": "PROGRAMMING AND DATA STRUCTURES",
            "teach_name": "張昭憲",
            "teach_name_en": "CHANG JAU-SHIEN",
            "note": "限本班生；有擋修                                                                                    ",
            "room": "B218"
        },
        {
            "weekno": "5",
            "sessno": "10",
            "week": "五",
            "sesstime": "17:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "5",
            "sessno": "11",
            "week": "五",
            "sesstime": "18:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "5",
            "sessno": "12",
            "week": "五",
            "sesstime": "19:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "5",
            "sessno": "13",
            "week": "五",
            "sesstime": "20:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "5",
            "sessno": "14",
            "week": "五",
            "sesstime": "21:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "6",
            "sessno": "01",
            "week": "六",
            "sesstime": "08:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "6",
            "sessno": "02",
            "week": "六",
            "sesstime": "09:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "6",
            "sessno": "03",
            "week": "六",
            "sesstime": "10:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "6",
            "sessno": "04",
            "week": "六",
            "sesstime": "11:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "6",
            "sessno": "05",
            "week": "六",
            "sesstime": "12:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "6",
            "sessno": "06",
            "week": "六",
            "sesstime": "13:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "6",
            "sessno": "07",
            "week": "六",
            "sesstime": "14:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "6",
            "sessno": "08",
            "week": "六",
            "sesstime": "15:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "6",
            "sessno": "09",
            "week": "六",
            "sesstime": "16:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "6",
            "sessno": "10",
            "week": "六",
            "sesstime": "17:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "6",
            "sessno": "11",
            "week": "六",
            "sesstime": "18:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "6",
            "sessno": "12",
            "week": "六",
            "sesstime": "19:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "6",
            "sessno": "13",
            "week": "六",
            "sesstime": "20:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        },
        {
            "weekno": "6",
            "sessno": "14",
            "week": "六",
            "sesstime": "21:10",
            "seatno": "",
            "ch_cos_name": "",
            "en_cos_name": "",
            "teach_name": "",
            "teach_name_en": "",
            "note": "",
            "room": ""
        }
    ]
}"""
    val myclassJson: JSONObject = JSONObject()
}
